spring:
  security:
    user:
      name: root
      password: root
  thymeleaf:
    enabled: true
    encoding: UTF-8
    cache: true
    check-template: true
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    root: info
    sun:
      rmi: error